[project]
dependencies = [
  "Jinja2==3.1.2",
  "wfdb==4.1.2"
]
name = "UNKNOWN"
version = "0.0.0"

[project.optional-dependencies]
dev = [
  "djlint==1.34.0",
  "mypy==1.6.1",
  "ruff==0.1.2",
  "ssort==0.11.6",
  "toml-sort==0.23.1"
]
