[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"Jinja2==3.1.2",
	"wfdb==4.1.2",
]

[project.optional-dependencies]
dev = [
	"black==23.7.0",
	"djlint==1.32.1",
	"mypy==1.5.1",
	"ruff==0.0.286",
	"ssort==0.11.6",
]
