[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"Jinja2==3.1.2",
	"wfdb==4.1.2",
]

[project.optional-dependencies]
dev = [
	"black==23.9.1",
	"djlint==1.34.0",
	"mypy==1.5.1",
	"ruff==0.0.291",
	"ssort==0.11.6",
]
