[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"Jinja2==3.1.2",
	"wfdb==4.1.1",
]

[project.optional-dependencies]
dev = [
	"black==23.3.0",
	"mypy==1.3.0",
	"ruff==0.0.272",
	"ssort==0.11.6",
]
