[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"Jinja2==3.1.2",
	"wfdb==4.1.0",
]

[project.optional-dependencies]
dev = ["ruff==0.0.192"]

[tool.ruff]
select = ["A", "C", "E", "ERA", "F", "I", "ICN", "N", "PD", "RET", "SIM", "T20", "TID", "UP", "W"]
ignore = ["C901", "E501", "PD013"]
fix = true
