name: reproducible-build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Certify paper reproducibility
        uses: pbizopoulos/reproducible-build-action@master
        with:
          make_call: "make"
