name: reproducible-build
on: [push, pull_request]
jobs:
  build-venv:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
      - name: make venv-verify
        run: make venv-verify
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@v2
        with:
          name: venv-${{ matrix.os }}
          path: ./ms.pdf
  build-docker:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: make docker-verify
        run: make docker-verify
      - name: Upload pdf for comparison
        uses: actions/upload-artifact@v2
        with:
          name: docker-${{ matrix.os }}
          path: ./ms.pdf
  release:
    if: contains(github.event.commit_head.message, '{release}')
    needs: [build-venv, build-docker]
    runs-on: ubuntu-20.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }} 
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1
          release_name: ${{ github.event.head_commit.message }} v1
          draft: false
          prerelease: false
  upload-release-assets:
    needs: [release]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        var: [venv, docker]
    steps:
      - name: Download pdfs from build
        uses: actions/download-artifact@v2
      - name: Create sha256sum var
        run: echo "::set-env name=sha256sumvar::$(sha256sum ${{ matrix.var }}-${{ matrix.os }}/ms.pdf | cut -d ' ' -f 1)"
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }} 
          asset_path: ./${{ matrix.var }}-${{ matrix.os }}/ms.pdf
          asset_name: ${{ matrix.var }}-${{ matrix.os }}-${{ env.sha256sumvar }}.pdf
          asset_content_type: application/pdf
