name: test-draft-version-document-reproducibility
on: [push, pull_request]
jobs:
  make:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Test draft version document reproducibility
        run: |
          make
          cp tmp/ms.pdf ms-previous.pdf
          rm -rf tmp/
          make
          cmp tmp/ms.pdf ms-previous.pdf
